def algoritmos():
	print(" =========================================================================")
	print("|             ALGORITMOS CRIPTOGRAFICOS                                   |")
	print("|                                                                         |")
	print("|SINTAXIS: python3 principal.py <algoritmo> <modo> <archivo> <llave> <alf>|")
	print("|                                                                         |")
	print("| <Algoritmo>:                                                            |")
	print("|     -cc Algoritmo Cesar                                                 |")
	print("|     -vg Algoritmo Vigenere                                              |")
	print("|     -ad Algoritmo Criptoanalisis de frecuencia                          |")
	print("|                                                                         |")
	print("| <modo>:                                                                 |")
	print("|     -c Cifrar                                                           |")
	print("|     -d Descifrar                                                        |")
	print("|                                                                         |")
	print("| <archivo>: Nombre del archivo a cifrar                                  |")
	print("|                                                                         |")
	print("| <llave>: -k [llave]                                                     |")
	print("|                                                                         |")
	print("| <alf>: -l [alfabeto]                                                    |")
	print("|                                                                         |")
	print("| Ejemplos:                                                               |")
	print("|     python3 principal.py -cc -c quijote.txt -k 5 -l es                  |")
	print("|     python3 principal.py -cc -d quijote.txt -l en                       |")
	print("|     python3 principal.py -vg -c quijote.txt -k ENERO -l es              |")
	print("|     python3 principal.py -ad -d quijote.txt -k WHISKY -l es             |")
	print(" =========================================================================")
	print(" =========================================================================")
	print("| Estudiante: Yilber Salazar   correo: yhsalazar@unicauca.edu.co          |")
	print("| Profesor: Ing. Siler Amador  correo: samador@unicauca.edu.co            |")
	print("| Universidad del Cauca 2018-II                                           |")
	print(" =========================================================================")

def cesar():
	print(" =========================================================================")
	print("|               ALGORITMOS CESAR                                          |")
	print("| SINTAXIS: python3 principal.py -cc <modo> <Archivo> [-k] [-l]           |")
	print("|                                                                         |")
	print("| <Archivo>: Nombre del archivo a cifrar                                  |")
	print("|                                                                         |")
	print("| <modo>:                                                                 |")
	print("|    -d   Parametro para descifrar                                        |")
	print("|    -c   Parametro para cifrar                                           |")
	print("| OPCIONAL                                                                |")
	print("|   [-k]  Bandera para agregar llave (Default: 3)                         |")
	print("|   [-l]  Bandera para agregar alfabeto (Default: es)                     |")
	print("|                                                                         |")
	print("| Ejemplos:                                                               |")
	print("|     python3 principal.py -cc -c quijote.txt                             |")
	print("|     python3 principal.py -cc -d quijote.txt -l en                       |")
	print("|     python3 principal.py -cc -c quijote.txt -k 7                        |")
	print("|     python3 principal.py -cc -d quijote.txt -k 2 -l es                  |")
	print(" =========================================================================")
	print(" =========================================================================")
	print("| Estudiante: Yilber Salazar	  correo: yhsalazar@unicauca.edu.co          |")
	print("| Profesor: Ing. Siler Amador  correo: samador@unicauca.edu.co            |")
	print("| Universidad del Cauca 2018-II                                           |")
	print(" =========================================================================")

def vigenere():
	print(" =========================================================================")
	print("|               ALGORITMO VIGENERE                                        |")
	print("| SINTAXIS: python3 principal.py -vg <modo> <Archivo> -k <clave>          |")
	print("|                                                                         |")
	print("| <Archivo>: Nombre del archivo a cifrar                                  |")
	print("|                                                                         |")
	print("| <modo>:                                                                 |")
	print("|    -d   Parametro para descifrar                                        |")
	print("|    -c   Parametro para cifrar                                           |")
	print("|                                                                         |")
	print("| <clave>: clave con el que se va a cifrar                                |")
	print("|                                                                         |")
	print("| OPCIONAL                                                                |")
	print("|   [-l]  Bandera para agregar alfabeto (Default: es)                     |")
	print("|                                                                         |")
	print("| Ejemplos:                                                               |")
	print("|     python3 principal.py -vg -c quijote.txt -k CASA                     |")
	print("|     python3 principal.py -vg -d quijote.txt -k LUNA -l en               |")
	print(" =========================================================================")
	print(" =========================================================================")
	print("| Estudiante: Yilber Salazar   correo: yhsalazar@unicauca.edu.co          |")
	print("| Profesor: Ing. Siler Amador  correo: samador@unicauca.edu.co            |")
	print("| Universidad del Cauca 2018-II                                           |")
	print(" =========================================================================")

def adfgvx():
	print(" =========================================================================")
	print("|               ALGORITMO ADFGVX                                          |")
	print("| SINTAXIS: python3 principal.py -ad <modo> <Archivo> -k <clave> -l <alf> |")
	print("|                                                                         |")
	print("| <Archivo>: Nombre del archivo a cifrar                                  |")
	print("|                                                                         |")
	print("| <modo>:                                                                 |")
	print("|    -d   Parametro para descifrar                                        |")
	print("|    -c   Parametro para cifrar                                           |")
	print("|                                                                         |")
	print("| <clave>: clave con el que se va a cifrar                                |")
	print("|                                                                         |")
	print("| <alf>:  Alfabeto que debe tener 36 caracteres                           |")
	print("|                                                                         |")
	print("| Ejemplos:                                                               |")
	print("|     python3 principal.py -ad -d quijote.txt -k WHISKY -l ES             |")
	print(" =========================================================================")
	print(" =========================================================================")
	print("| Estudiante: Yilber Salazar   correo: yhsalazar@unicauca.edu.co          |")
	print("| Profesor: Ing. Siler Amador  correo: samador@unicauca.edu.co            |")
	print("| Universidad del Cauca 2018-II                                           |")
	print(" =========================================================================")
	
def mensaje():
	print(" =========================================================================")
	print("| Estudiante: Yilber Salazar   correo: yhsalazar@unicauca.edu.co          |")
	print("| Profesor: Ing. Siler Amador  correo: samador@unicauca.edu.co            |")
	print("| Universidad del Cauca 2018-II                                           |")
	print(" =========================================================================")
	
    
